# Generated by Django 4.0.3 on 2022-03-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0003_alter_livro_co_autor_alter_livro_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='data_cadastro',
            field=models.DateField(auto_now=True),
        ),
    ]
