# Generated by Django 4.0.3 on 2022-03-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0004_emprestimo_nome_emprestado_anonimo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='tempo_duracao',
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
