# Generated by Django 4.0.3 on 2022-03-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0005_remove_emprestimo_tempo_duracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='avaliacao',
            field=models.CharField(choices=[('P', 'Péssimo'), ('R', 'Ruim'), ('M', 'Médio'), ('B', 'Bom'), ('O', 'Ótimo')], default=1, max_length=1),
        ),
    ]
