# Generated by Django 4.0.3 on 2022-03-16 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0005_alter_livro_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='data_cadastro',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
