# Generated by Django 4.0.3 on 2022-03-17 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0008_categoria_livro_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='categoria',
        ),
    ]
