# Generated by Django 4.0.3 on 2022-03-23 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0009_avaliacao_alter_emprestimo_avaliacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='capa_livro'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 15, 5, 40, 826721)),
        ),
    ]
