# Generated by Django 4.0.3 on 2022-03-23 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0011_alter_emprestimo_data_emprestimo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avaliacao',
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 17, 18, 11, 24685)),
        ),
    ]
